name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          # auto-merge rules are in /.github/auto-merge.yml
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}