name: Compatibility Test
on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request: {}
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  compat-test:
    name: Compat Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version-file: 'go.mod'
        check-latest: true
      id: go
    - name: Compat Test
      run: make compat-tests
    - name: Upload Logs
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: logs
        path: .logs/**/*.log
        if-no-files-found: ignore
      if: ${{ always() }}
