name: Provider Test
on: [push]
jobs:
  endurance-test:
    name: Provider Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go.
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Provider Tests
      run: make provider-tests
